name: Node CI

on: [push]

jobs:
  build-and-test:
    name: Build and test code
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm build
        npm run test:ci
      env: 
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
  release-and-deploy:
    name: Release to NPM registry
    if: github.ref == 'master'
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: publish and deploy
      run: | 
        npm install
        npm run semantic-release
        now="npx now --debug --token=$NOW_TOKEN"
        echo "$ now rm --safe --yes delete-merged-branch"
        $now rm --safe --yes delete-merged-branch
        echo "$ now --public"
        $now --public
        echo "$ now alias"
        $now alias
      env: 
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
    
    
