name: Node CI

on: [push]

jobs:
  build-and-test:
    name: Build and test code
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm build
        npm run test:ci
      env: 
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  sonarcloud-scan:
    name: Sonarcloud scan      
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
  release-and-deploy:
    name: Release to NPM registry and deploy to ZEIT
    needs: [build-and-test, sonarcloud-scan]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'  
    steps:
    - uses: actions/checkout@v1
    - name: Setup Google Cloud SDK
      uses: mathrix-education/setup-gcloud@1.2.1
      with:
        service-account-key: ${{ secrets.GCP_ACCOUNT_KEY }}
        # The default Google Cloud project. You can change it later.
        project: delete-merged-branch
#     - name: publish
#       run: | 
#         npm install
#         npm run semantic-release
#       env: 
#         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: deploy
      run: |
        echo -e $GCP_TOKEN >> ~/.gcloud/keyfile.json
        curl -o- -L https://slss.io/install | bash
        serverless deploy -v
      env: 
        GCP_TOKEN: ${{ secrets.GCP_ACCOUNT_KEY }}
    
